// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitController(conf int, name string) *Controller {
	model := NewModel(name)
	logic := NewLogin(conf)
	controller := NewController(model, logic)
	return controller
}
